// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/09/2025, 16.23.35
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/FELIX/ruangoffice-new/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/FELIX/ruangoffice-new/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/FELIX/ruangoffice-new/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/FELIX/ruangoffice-new/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/FELIX/ruangoffice-new/plugins/**/*.{js,ts,mjs}","C:/Users/FELIX/ruangoffice-new/composables/**/*.{js,ts,mjs}","C:/Users/FELIX/ruangoffice-new/utils/**/*.{js,ts,mjs}","C:/Users/FELIX/ruangoffice-new/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/FELIX/ruangoffice-new/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/FELIX/ruangoffice-new/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/FELIX/ruangoffice-new/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;